# -*- coding: utf-8 -*-
TITLE = "Historical process fidelity does not constrain future extreme rainfall in the United Arab Emirates, and the reasons are measurable"

ABSTRACT = """Extreme rainfall in hyperarid regions is produced by a small number of intense storms, making future changes difficult to project. We tested whether climate models that better reproduce historical circulation and moisture transport give more reliable projections of extreme rainfall in the United Arab Emirates, and quantified why such tests fail. Gauge observations, a gauge-anchored CHIRPS field, ERA5 circulation diagnostics and downscaled CMIP6 projections were combined. A clear west-east rainfall gradient is resolved by all three gauge sources, with gauge-only east/west ratios of 1.67 for annual rainfall and 2.06 for annual maximum one-day precipitation (Rx1day); leave-one-station-out testing showed that CHIRPS correction factors were not transferable between locations, so the corrected field was used only for climatological spatial completion. We evaluated 21 CMIP6 models with a precipitation-independent score of circulation and moisture-transport fidelity, and tested four predictor classes against projected change across an ensemble expanded to 33 downscaled models drawn from 17 model families. None carried out-of-sample skill for Rx1day or very wet-day precipitation (R95p) under SSP5-8.5, including the observed historical warming trend on which published constraints on extreme precipitation rest, and no relationship survived false-discovery correction. Three properties of the data explain this outcome. Finite-period sampling accounts for 27-46 % of the inter-model spread in absolute change, and where change is expressed as a fraction of a small baseline the within-model sampling variance equals or exceeds the spread across models, making fractional change an unstable predictand. Bias-corrected downscaling removes roughly 85-89 % of the normalised inter-model spread in present-day extremes and leaves what remains largely uncorrelated with the parent model, eliminating the information a bias-type predictor requires. And a predictor formed from a model own present-day level appears to succeed only through sampling error shared with the denominator of fractional change: recomputing predictor and baseline from disjoint seasons reverses the sign, and the confound survives cross-validation, bootstrap resampling, permutation testing and family jackknifing. Projected change is dominated by the component outside Clausius-Clapeyron scaling and scales with projected regional warming at rates well above it. The observed eastward gradient and moisture pathway are robust, whereas historical process fidelity provides little constraint on future extreme-rainfall change, for reasons that are now quantified rather than inferred."""

KEYWORDS = "Keywords: extreme rainfall; hyperarid climate; CMIP6; moisture transport; model evaluation; emergent constraints; downscaling uncertainty; United Arab Emirates"

INTRO_Q = """The analysis addresses five questions. First, how consistently do 19 gauge sites resolve the UAE rainfall gradient, and do gauge-derived CHIRPS corrections transfer between stations? Second, how well do 21 CMIP6 models reproduce the ERA5-based UAE Rainfall Circulation Signature (URCS) without using simulated precipitation? Third, do process fidelity, historical extreme level, present-day variability, or the observed historical warming trend predict projected Rx1day and R95p changes under SSP5-8.5 after family-wise cross-validation, multiplicity control, and coupling tests? Fourth, how much of the apparent inter-model spread is systematic rather than finite-period sampling, and how much of the systematic component survives bias-corrected downscaling? Finally, how sensitive are the projections to the downscaling product for five common parent models?"""

METHODS_22_ADD = """The projection ensemble was subsequently expanded beyond the 15 models carrying Process Fidelity Scores. All NEX-GDDP-CMIP6 models with both historical and SSP5-8.5 daily precipitation for the required seasons were included, giving 33 models after the exclusion of MRI-ESM2-0, which lacks an SSP5-8.5 realisation, and of GFDL-CM4_gr2 and GFDL-ESM41, which are alternative-grid copies of GFDL-CM4 and GFDL-ESM4 identified by identical domain-mean warming to four decimal places. Models were assigned to 17 families by genealogy rather than institution, grouping NorESM2 and TaiESM1 with CESM, NESM3 with MPI, and KACE-1-0-G and UKESM1-0-LL with HadGEM on the basis of shared atmospheric components. Process-fidelity tests remain at 15 models because upper-air fields are unavailable for the additional members; ACCESS-CM2 is therefore excluded from process scoring but included in the projection ensemble. For the comparison of raw and downscaled spread, raw CMIP6 daily precipitation on native grids was obtained from the Earth System Grid Federation for the 30 models with complete 1990-2014 coverage, of which 27 matched a NEX-GDDP-CMIP6 model."""

METHODS_26_ADD = """Four further analyses were added to the protocol. The share of inter-model variance attributable to finite-period sampling was estimated by resampling the 25 seasons of each model and period with replacement 5,000 times and recomputing the projected change, giving a within-model sampling standard deviation whose mean square was compared with the variance of projected change across models. This partition was computed for both absolute and fractional change, because the two behave differently where the baseline is small.

Because the present-day-level predictor is the same quantity that appears in the denominator of fractional change, two controls for shared sampling error were applied. The correlation expected from that sharing alone was estimated by resampling seasons within each model and period and recomputing both predictor and projected change from the same resample, repeated 2,000 times. A split-sample estimate was then constructed in which the predictor was computed from the odd-numbered historical seasons and the baseline of the projected change from the even-numbered seasons, so that no observation is shared; this was evaluated for both fractional and absolute change and subjected to the same cross-validation, permutation, bootstrap and jackknife procedures as the primary tests.

To assess how much inter-model information in present-day extreme rainfall survives bias-corrected downscaling, both indices were computed for 1990-2014 from raw CMIP6 output on each model's native grid and from the NEX-GDDP-CMIP6 equivalent using identical domain, season and index definitions. Spread was compared as the coefficient of variation across models, which is dimensionless and therefore insensitive to the difference in mean level between grids, and correspondence between versions was measured by the across-model correlation of present-day level. Native grids contain between 2 and 64 cells within the domain against 667 for the downscaled product, so only normalised spread and correspondence were compared.

Finally, projected change was partitioned into a thermodynamic term, defined as Clausius-Clapeyron scaling at 7 % per kelvin applied to each model's own projected regional warming, and a residual, with variance shares computed from their sum. Projected regional warming, the difference in domain-mean annual near-surface air temperature between 2076-2100 and 1990-2014, was additionally related to projected change; it is a model output rather than an observable and is therefore reported as a scaling relationship and not as a constraint. The observed historical warming trend over 1980-2014, computed by ordinary least squares on each model's domain-mean annual temperature, was added as a fourth predictor because it is the predictor class on which published constraints on extreme precipitation rest. Temperature data were unavailable for CMCC-CM2-SR5, so warming-based analyses use 32 models. All random procedures used seed 20260918."""

RESULTS_36_NEW = """Historical PFS was tested against SSP5-8.5 changes in wet-season Rx1day and R95p for 2076-2100 relative to 1990-2014. The analysis used 15 models for the UAE and eastern domains; the latter comprises six NEX-GDDP grid cells. Because PFS is an unsigned distance from the reference state, the test evaluates performance weighting rather than a formal emergent constraint.

PFS provides no predictive skill for any index-region combination (Table 8; Fig. 9). Family-weighted correlations are small (|r| <= 0.15, p >= 0.61), leave-one-model-out skill is negative (-0.22 to -0.53), and leave-one-family-out skill is lower (-0.50 to -1.02). Weighting changes ensemble spread by -14 % to +4 %, less than the bootstrap uncertainty in spread (95 % interval half-width = 24-47 %). At n = 15, correlation intervals remain wide; for PFS versus UAE Rx1day, r = -0.03 (95 % CI -0.53 to +0.49). Strong predictive relationships are therefore excluded, but weak relationships remain unresolved. Bootstrap resampling of the national Rx1day relationship returns a sign stability of 0.50, so the sign of the correlation is determined by resampling alone. Testing the components separately produces the same result, and the composite performs worse than several of its own inputs: the IVT pattern term, which carries 35 % of the weight, returns the lowest cross-validated skill of any predictor-index-region combination examined (leave-one-family-out skill -1.22), whereas the 500-hPa term, carrying 10 %, returns the strongest raw correlations among the components (r = -0.41 nationally and -0.49 in the east for Rx1day). The minimum Benjamini-Hochberg q-value across 44 tests is 0.66.

Expanding the ensemble to 33 models does not alter this conclusion for the predictors that can be evaluated at that size. Projected changes remain wide and cross zero: UAE Rx1day changes by +13.6 % on average with an inter-model standard deviation of 31.5 % and a range from -32.7 % to +79.7 %, and R95p by +75.0 % with a standard deviation of 106.5 % and a range from -46.2 % to +331.9 %. Twenty of 33 models project an Rx1day increase and 22 of 33 an R95p increase, neither distinguishable from an even split (binomial p = 0.296 and 0.080). The observed historical warming trend achieves correlations between +0.21 and +0.35 (p = 0.052 to 0.253) with leave-one-family-out skill between -0.07 and +0.05, and no cell approaches significance under false-discovery control (minimum q = 0.144). The expanded ensemble is adequately powered for this test: at n = 33 the smallest correlation detectable with 80 % power at alpha = 0.05 is |r| = 0.47, rising to |r| = 0.54 under four-test correction.

Finite-period uncertainty is large relative to the projected signal, and its magnitude depends on how change is expressed. Resampling the 25 wet seasons in each period places zero within the 95 % interval for 73 % of model-index-region combinations at 15 models (Fig. 9e) and for 21 to 25 of 33 models in the expanded ensemble. Expressed as absolute change, sampling accounts for 32 % and 46 % of the UAE and eastern Rx1day spread and 28 % and 36 % of the corresponding R95p spread at 33 models, consistent with the 37-48 % obtained at 15 models. Expressed as fractional change, however, the mean within-model sampling variance reaches 89 % of the inter-model variance for UAE R95p and 102 % for the eastern domain, and exceeds it at 15 models. A ratio at or above unity means that an individual model's percentage change varies more under seasonal resampling than the projected changes vary across models. Fractional change is therefore an unstable predictand where the baseline is small, and this instability is the same property that generates the denominator coupling reported below. Because only one realisation is available per model, all of these fractions are lower bounds on unforced variability (Fig. S2).

Candidate-predictor tests identify no robust relationship on the published predictand (Table 9). Historical Rx1day versus percentage change is the sole nominal result (r = -0.58, p = 0.022; leave-one-model-out skill = 0.024), but the historical value also appears in the predictand denominator. Permuting future values reproduces the correlation (median r = -0.58; 95 % range -0.82 to -0.20; coupling probability = 0.49), whereas future Rx1day level is unrelated to the historical level (r = 0.03, p = 0.90). The association fails false-discovery control (q = 0.20), becomes non-significant after removal of the CESM family (p = 0.13), and is absent for R95p and the eastern domain. No PFS weighting scheme yields |r| > 0.33.

Two further tests establish the magnitude of that coupling and its consequence. Resampling seasons within each model and recomputing both predictor and change from the same resample produces a correlation of -0.47 for national Rx1day (95 % range -0.62 to -0.28) and -0.47 for national R95p (-0.65 to -0.23) from sampling noise alone, in both cases larger in magnitude than the correlations observed. Recomputing the predictor from the odd-numbered historical seasons and the baseline from the even-numbered seasons, so that no observation is shared, reverses the sign in every cell: from -0.37 to +0.09 for national Rx1day, from -0.38 to +0.45 for national R95p, and from -0.35 to +0.52 for eastern R95p. The confounded relationship had passed leave-one-out and leave-one-family-out cross-validation, bootstrap sign stability, family-deletion jackknifing and permutation testing, so the conventional robustness battery does not detect it.

With the confound removed and change expressed in absolute units against an independent baseline, a positive relationship remains for the accumulated index alone. National R95p returns r = +0.43 (permutation p = 0.012) with leave-one-out and leave-one-family-out skill of +0.13, bootstrap sign stability 0.995, and positive skill in 17 of 17 family deletions; eastern R95p returns r = +0.50 (permutation p = 0.003), skill of +0.20 and +0.21, sign stability 1.000, and 17 of 17. Rx1day returns no resolved relationship in either region (r = +0.11 and +0.17, permutation p = 0.556 and 0.364, negative leave-one-family-out skill). Models producing more very wet-day precipitation today therefore project larger absolute increases, the opposite direction to the confounded estimate. Section 3.7 shows that this relationship is a property of the downscaled product rather than of the parent models.

Projection magnitude also depends strongly on the downscaling product. Across the full ensembles, UAE Rx1day change ranges from -35 % to +62 % in NEX-GDDP and from -13 % to +131 % in ISIMIP3b. For five common parent models analysed with identical masks, periods, and index definitions, NEX-GDDP changes are 12-110 percentage points smaller in all ten parent-index comparisons, and four comparisons differ in sign (Fig. 11). Matched-parent Rx1day ranges are -25 % to +75 % in NEX-GDDP and -13 % to +131 % in ISIMIP3b. The bias-adjustment and downscaling workflow therefore contributes substantial projection uncertainty.

Taken together, cross-validation, multiplicity control, coupling tests, family-dependence analysis, resampling, and the matched-parent comparison provide no evidence that the evaluated historical metrics constrain projected UAE rainfall extremes."""

RESULTS_37_NEW_HEAD = "3.7 Effect of bias-corrected downscaling on inter-model spread"
RESULTS_37_NEW = """Statistical downscaling removes most of the inter-model information in present-day extreme rainfall. For the 27 models available both as raw CMIP6 output and as NEX-GDDP-CMIP6, the coefficient of variation of present-day wet-season Rx1day across models falls from 0.463 in the raw output to 0.178 after bias-corrected downscaling, retaining 14.8 % of the normalised variance; for R95p it falls from 0.576 to 0.194, retaining 11.4 %. Raw present-day R95p ranges from 1.6 to 23.2 mm across models and the downscaled equivalent from 2.3 to 10.6 mm.

The correspondence between a model's raw and downscaled present-day level is weak for Rx1day (r = +0.26) and indistinguishable from zero for R95p (r = -0.03). A model's downscaled present-day extreme rainfall is therefore largely independent of its parent's. The anomalously low downscaled Rx1day of KACE-1-0-G, 4.86 mm against an ensemble mean of 14.0 mm, corresponds to 15.91 mm in the raw output and is a property of the downscaling rather than of the model.

Native grids contain between 2 and 64 cells within the domain against 667 for the 0.25 degree downscaled product, so mean levels are not comparable between versions and only normalised spread and correspondence are compared. Part of the variance reduction may therefore reflect the difference in resolution as well as the bias adjustment; a control degrading the downscaled field to each parent's native grid has not been performed."""

RESULTS_38_NEW_HEAD = "3.8 Thermodynamic and dynamic partition, and scaling with regional warming"
RESULTS_38_NEW = """Inter-model spread is dominated by the component not explained by Clausius-Clapeyron scaling of regional warming. Partitioning each model's projected change into a thermodynamic term, computed as 7 % per kelvin of its own projected regional warming, and a residual, the residual accounts for 88.9 % of the combined variance for national Rx1day and 86.6 % for eastern Rx1day. For R95p the residual share is 99.0 % nationally and 98.9 % in the east, the thermodynamic term contributing approximately 1 % in both regions. The residual is defined by subtraction and therefore absorbs internal variability, model error and any non-Clausius-Clapeyron thermodynamic contribution alongside circulation-driven change.

Projected change nevertheless scales with projected regional warming at rates substantially above the Clausius-Clapeyron value, and every index and region is resolved. Across 32 models spanning a regional warming range of 3.61 to 7.65 K, national Rx1day change increases at 15.6 % per kelvin (r = +0.50, p = 0.0035) and national R95p change at 56.4 % per kelvin (r = +0.54, p = 0.0013); eastern rates are 11.1 % and 42.6 % per kelvin (r = +0.42, p = 0.018; r = +0.45, p = 0.009). All four cells return positive leave-one-out and leave-one-family-out skill, between +0.11 and +0.25, and all four survive Benjamini-Hochberg control (q = 0.005 to 0.018). The national relationships return bootstrap sign stabilities of 0.999 and 1.000 and positive leave-one-family-out skill in 17 of 17 family deletions. Projected regional warming is a model output rather than an observable, so this relationship characterises inter-model behaviour and does not constrain the projections."""

DISC_44_NEW = """The central projection result is the absence of a validated historical-to-future relationship. Neither PFS, historical extreme magnitude, present-day variability, nor the observed historical warming trend predicts Rx1day or R95p change under the pre-specified tests (Figs. 9 and 10; Tables 8 and 9). Present-day variability, which constrains extratropical projections in other settings (Zhang et al., 2022), provides no out-of-sample skill for the UAE. That the observed warming trend also fails is notable, because it is the predictor class on which the published constraints on extreme precipitation rest.

This null result is consistent with the construction of PFS. An unsigned distance from a present-day reference state has no prescribed relationship with forced change, which also depends on thermodynamic moisture increases and event-scale dynamics. The partition reported in Section 3.8 supplies direct evidence for the second clause: between 87 % and 99 % of the inter-model spread lies outside Clausius-Clapeyron scaling of each model's own warming, so the quantity the score is asked to predict is dominated by circulation change rather than by the mean thermodynamic state the score describes. A defensible emergent constraint requires a specified physical link and out-of-sample validation (Hall et al., 2019); the present PFS satisfies neither condition. That the composite performs worse than several of its own components, having placed 80 % of its weight on the least informative of them, is a further argument that composite skill scores should be validated against their constituents before being used for model selection.

The nominal association between historical extreme level and fractional change arises because the historical value appears in both the predictor and the denominator of percentage change. Permutation and alternative-predictand tests identify the relationship as mathematical rather than physical, and two further analyses establish its magnitude and its consequence. Seasonal resampling shows that shared sampling error alone produces a correlation of approximately -0.47, larger than the correlation observed, and a split-sample estimate in which predictor and baseline are computed from disjoint seasons reverses the sign in every index-region combination. What lies beneath the confound is a positive relationship for the accumulated index: models producing more very wet-day precipitation today project larger absolute increases.

Two points follow that generalise beyond this region. First, the confounded relationship passed leave-one-family-out cross-validation, bootstrap sign stability, permutation testing and family jackknifing. Each of those tests asks whether a relationship is stable across models; none asks whether it exists in the absence of shared sampling error, and because the artifact is present in every model it transfers perfectly. A split-sample test using disjoint periods for predictor and baseline is cheap, general, and should accompany any constraint whose predictor appears in the denominator of its predictand. Second, the instability of fractional change documented in Section 3.6, where within-model sampling variance equals or exceeds inter-model variance for R95p, indicates that constraint tests should be conducted on absolute change wherever the baseline is small and noisy. Historical-to-relative-change analyses therefore require explicit coupling diagnostics before being interpreted as emergent constraints.

The analysis shows that the tested metrics contain no detectable predictive information in the available ensemble. It does not exclude weaker relationships or constraints based on event-conditioned diagnostics."""

DISC_45_NEW = """The signal-to-noise structure limits the power of the constraint test. Finite-period sampling accounts for 27-46 % of inter-model spread in absolute change across the expanded ensemble, consistent with the 37-48 % obtained at 15 models, and zero lies within the resampled interval for 73 % of model-index-region combinations (Fig. S2). These estimates are lower bounds because only one realisation is available per model. The effective sample also contains only 17 model families among 33 models, and nine among the 15 carrying process scores. Much of the apparent cross-model spread is therefore unforced variability rather than a stable forced response.

A second and previously unexamined mechanism compounds this. Bias-corrected downscaling removes approximately 85 % of the normalised inter-model variance in present-day Rx1day and 89 % in R95p, and the correspondence between a model's raw and downscaled present-day level is weak for Rx1day and absent for R95p (Section 3.7). This is the expected consequence of the procedure rather than a defect in it: bias-corrected downscaling is designed to bring each model's present-day distribution toward observations, and the inter-model spread in that distribution is precisely what it removes. The consequence for constraint analysis is nevertheless material. A constraint built on a present-day bias predictor requires that models differ systematically in the predictor and that those differences carry information about the model; after bias-corrected downscaling neither condition holds. The positive relationship that survives the confound in Section 3.6 should accordingly be read as a property of the downscaled product rather than as a statement about model fidelity, which does not make it uninformative, since such products rather than raw model output are what regional impact assessment uses, but does bound what it can be said to mean. Constraint studies work with raw model output while impact studies work with downscaled products, so this issue has not previously arisen.

Matched-parent comparisons reveal additional uncertainty after the global model simulation. NEX-GDDP changes are 12-110 percentage points smaller than ISIMIP3b changes across ten parent-index comparisons, and four comparisons reverse sign (Fig. 11). Projection spread therefore combines global model structure, internal variability, the loss of between-model information in bias adjustment, and the choice of downscaling workflow. Ranking parent models by circulation fidelity cannot remove uncertainty introduced at later processing stages. Regional assessments should report matched-parent and multi-product sensitivity rather than treat one downscaled archive as a unique representation of the parent response."""

DISC_47_ADD = """Three further limitations attach to the analyses added in this revision. The comparison of raw and downscaled spread confounds resolution with bias adjustment, because native grids contain between 2 and 64 cells within the domain against 667 for the downscaled product; a control degrading the downscaled field to each parent's native grid would separate these and has not been performed. The thermodynamic and dynamic partition is defined by subtraction, so the residual absorbs internal variability and model error alongside circulation-driven change and should not be equated with a forced dynamic response. Finally, process-fidelity tests rest on 15 models while the remaining predictor tests rest on 32 or 33, because upper-air fields are unavailable for the additional members; the process-fidelity result is therefore the least well-powered element of the analysis, and a weak relationship below the detection threshold at that sample size cannot be excluded."""

CONCLUSIONS_NEW = """Gauge observations establish a persistent west-east gradient in UAE rainfall extremes, supported by a coherent Arabian Sea-Gulf of Oman moisture pathway. The gauge-only GSOD comparison gives east/west ratios of 1.67 for annual rainfall and 2.06 for Rx1day, whereas station-corrected CHIRPS yields a smaller domain-scale Rx1day ratio of 1.32 and is suitable only for climatological spatial completion. Beyond this present-day spatial pattern, the available evidence does not support a robust historical trend or a strong constraint on future extreme-rainfall change. Across an ensemble expanded to 33 models from 17 families, neither historical process fidelity, nor present-day extreme level, nor present-day variability, nor the observed historical warming trend predicted projected Rx1day or R95p change under SSP5-8.5 with out-of-sample skill.

Three measurable properties of the data account for this outcome. Finite-period sampling accounts for a quarter to a half of the inter-model spread in absolute change, and where change is expressed as a fraction of a small baseline the within-model sampling variance equals or exceeds the spread across models, making fractional change an unstable predictand and generating a spurious negative association that survives cross-validation, bootstrap resampling, permutation testing and family jackknifing. Bias-corrected downscaling removes roughly seven-eighths of the normalised inter-model spread in present-day extreme rainfall and leaves what remains largely uncorrelated with the parent model, eliminating the information a bias-type predictor requires. And the projected change is dominated by the component outside Clausius-Clapeyron scaling, which a score describing the mean circulation state does not address.

For practice, three recommendations follow. Constraint tests should be conducted on absolute rather than fractional change wherever the baseline is small and noisy, and should include a split-sample diagnostic in which predictor and baseline are computed from disjoint periods. Constraint analysis on statistically downscaled ensembles should not use present-day bias predictors without first establishing that the downscaling has preserved the inter-model information those predictors require. And UAE climate-risk assessments should retain the well-supported spatial gradient but represent future change using the full ensemble and product-dependent range. Narrowing that range will depend on lowering the sampling floor through longer records or initial-condition ensembles, on constraining the regional temperature response, and on the treatment of the post-processing chain, rather than on selecting models by present-day skill."""
